on:
  push:
    branches:
      - main

jobs:
  generate_rules:
    runs-on: ubuntu-latest
    name: Generate Rules from SLOs
    steps:
      - uses: actions/checkout@v3
      - name: Generate rule files
        id: generate
        uses: ArthurSens/pyrra-generate-action@v1
        with:
          configFiles: "examples/*.yaml"
          outputFolder: "/tmp/output/"
          genericRules: true
      - name: Upload to mimir
        uses: ArthurSens/mimirtool-rules-load-action@v1
        with:
          address: ${{ secrets.MIMIR_ADDRESS }}
          id: ${{ secrets.MIMIR_TENANT_ID }}
          key: ${{ secrets.MIMIR_API_KEY }}
          user: ${{ secrets.MIMIR_USER }}
          ruleFilesPath: /tmp/output/*.yaml
